### ISSUE TITLE
[Summit Voices] Setup dev site

### ISSUE THREAD

**Issue by tieralanier** [s360/summitvoices-dev#1]
Hi Bintang,

Please setup a new dev site summitvoices-dev.s360.is

And transfer all content from http://summitvoices.com/

Thanks!

**Comment by halilintar8** [comment]
Hi Tiera,

done,
lenoir1
sftp = summitvoices-dev.s360.is, summit, VlmEZmkCHTCa
wp_db = summit_dev, summit_dev, p88HpOHF2lRz
wp-admin (lastpass) = upwardstech, VlmEZmkCHTCa

Thanks.
